# GENERAL SETTINGS
GENERAL_OUTPUT_FILENAME = r"OUT_%d-%m-%Y_%H-%M.mp4"

# REDDIT API SETTINGS
REDDIT_API_USER_AGENT = r"CHANGEME"
REDDIT_API_CLIENT_ID = r"CHANGEME"
REDDIT_API_CLIENT_SECRET = r"CHANGEME"

REDDIT_API_SUBREDDIT_LISTS = ["AskReddit"]
REDDIT_API_MAX_POSTS_TO_DOWNLOAD = 5
REDDIT_API_MIN_CHARS_PER_POST = 50

# OPEN-AI SETTINGS
OPENAI_API_KEY = r"CHANGEME"
OPENAI_AUDIO_OUTPUT_PATH = r"working_dir\audio.mp3"
OPENAI_CAPTION_OUTPUT_PATH = r"working_dir\caption_data"
OPENAI_TTS_VOICE = r"alloy"
OEPNAI_MAX_CHARS_FOR_REQUEST = 4095

#MOVIEPY SETTINGS
MOVIEPY_PATH_TO_BACKROUND_VIDEOS = r"backround_video"
MOVIEPY_VIDEO_OUTPUT_DIRECTORY = r"output"
MOVIEPY_VIDEO_CODEC = r"libx264"
MOVIEPY_AUDIO_CODEC = r"aac"
MOVIEPY_MOVIEPY_OUTPUT_FPS = 30
MOVIEPY_GAMEPLAY_START_OFFSET = 5
MOVIEPY_VIDEO_DIMENSIONS = 405, 720


